version: "3.9"

services:
  django:
    image: ryan881225/backend-django:latest
    ports:
      - "8000:8000" 
      - "8001:8000" 
    depends_on:
      - mysql
    container_name: web_django
    command: >
      daphne -b 0.0.0.0 -p 8000 my_backend.asgi:application


  mysql:
    image: ryan881225/hw-mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hw_db
      MYSQL_USER: hw_user
      MYSQL_PASSWORD: hw_pass
      MYSQL_ROOT_PASSWORD: root_pass
    container_name: hw_mysql
